packages:
  - packages/core/*
  - packages/transports/*
  - packages/plugins/*
  - packages/context-managers/*
  - packages/log-level-managers/*
  - packages/mixins/*
  - docs

ignoredBuiltDependencies:
  - '@datadog/native-appsec'
  - '@datadog/native-iast-taint-tracking'
  - '@datadog/native-metrics'
  - '@datadog/pprof'
  - dd-trace

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - lefthook
  - protobufjs
  - dtrace-provider
