# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Build LogLayer Docs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm # or pnpm / yarn

      - name: Install dependencies
        run: pnpm install
        working-directory: docs

      - name: Build with VitePress
        run: pnpm run docs:build
        working-directory: docs
        env:
          BASE_URL: 'https://loglayer.dev'
