name: Lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'packages/**'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install turbo
        run: pnpm install turbo --global

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspace packages
        run: turbo build

      - name: Run package checking
        run: pnpm run lint:packages

      - name: Run type checking
        run: turbo verify-types

      - name: Run linting
        run: turbo lint
