name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'packages/**'

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.11.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspace packages
        run: pnpm build

      - name: Run Package Tests
        run: |
          pnpm run test
